cameras:
  left_camera_serial: ""
  right_camera_serial: ""
  top_camera_serial: ""

motors:
  left:
    1: 6   # DM8009
    2: 6
    3: 2   # DM4340
    4: 2
    5: 0   # DM4310
    6: 0
    7: 0  # J7 (DM4310)
    8: 0  # Gripper (DM4310)
  right:
    1: 6   # DM8009
    2: 6
    3: 2   # DM4340
    4: 2
    5: 0   # DM4310
    6: 0
    7: 0
    8: 0  # Gripper (DM4310)

control:
  active:
    kp: 40.0
    kd: 1.5
  passive:
    kp: 0.0
    kd: 0.1
  gripper:
    kp: 20.0  # Slightly softer than arm joints
    kd: 0.1   # Minimal damping
